# Sets default memory used for gradle commands. Can be overridden by user or command line properties.
org.gradle.jvmargs=-Xmx2G
org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.caching=true
org.gradle.configuration-cache=false

# Minecraft version and NeoForge version (must agree)
minecraft_version=1.21.1
minecraft_version_range=[1.21.1]
neo_version=21.1.249
loader_version_range=[1,)

## Mod Properties
mod_id=easycraftchest
mod_name=Easy Craft Chest
mod_license=All Rights Reserved
mod_version=1.0.4
mod_group_id=com.easycraftchest
